# Generated by Django 5.2.8 on 2025-11-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_experience', models.BooleanField(default=True, help_text='Check if you already have something to post about.')),
                ('topic_type', models.CharField(choices=[('project', 'Project'), ('event', 'Event'), ('job', 'Job / Internship'), ('learning', 'Learning / Course'), ('other', 'Other')], default='project', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Describe the experience (if you have one).')),
                ('key_learnings', models.TextField(blank=True, help_text='What did you learn or accomplish?')),
                ('image', models.ImageField(blank=True, help_text='Image to attach to this LinkedIn post.', null=True, upload_to='linkedin_images/')),
                ('draft_text', models.TextField(blank=True)),
            ],
        ),
    ]
