# Generated by Django 5.2.8 on 2025-11-15 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_linkedinaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinaccount',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
